// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Block        string
	Exchange     string
	ExchangeTick string
	Mempool      string
	PowData      string
	VSP          string
	VSPTick      string
}{
	Block:        "block",
	Exchange:     "exchange",
	ExchangeTick: "exchange_tick",
	Mempool:      "mempool",
	PowData:      "pow_data",
	VSP:          "vsp",
	VSPTick:      "vsp_tick",
}
