// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Block        string
	Exchange     string
	ExchangeTick string
	Github       string
	Mempool      string
	NetworkPeer  string
	PowData      string
	Reddit       string
	Twitter      string
	Vote         string
	VSP          string
	VSPTick      string
	Youtube      string
}{
	Block:        "block",
	Exchange:     "exchange",
	ExchangeTick: "exchange_tick",
	Github:       "github",
	Mempool:      "mempool",
	NetworkPeer:  "network_peer",
	PowData:      "pow_data",
	Reddit:       "reddit",
	Twitter:      "twitter",
	Vote:         "vote",
	VSP:          "vsp",
	VSPTick:      "vsp_tick",
	Youtube:      "youtube",
}
