// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Exchanges", testExchanges)
	t.Run("ExchangeTicks", testExchangeTicks)
	t.Run("VSPS", testVSPS)
	t.Run("VSPTicks", testVSPTicks)
	t.Run("VSPTickTimes", testVSPTickTimes)
}

func TestDelete(t *testing.T) {
	t.Run("Exchanges", testExchangesDelete)
	t.Run("ExchangeTicks", testExchangeTicksDelete)
	t.Run("VSPS", testVSPSDelete)
	t.Run("VSPTicks", testVSPTicksDelete)
	t.Run("VSPTickTimes", testVSPTickTimesDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Exchanges", testExchangesQueryDeleteAll)
	t.Run("ExchangeTicks", testExchangeTicksQueryDeleteAll)
	t.Run("VSPS", testVSPSQueryDeleteAll)
	t.Run("VSPTicks", testVSPTicksQueryDeleteAll)
	t.Run("VSPTickTimes", testVSPTickTimesQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Exchanges", testExchangesSliceDeleteAll)
	t.Run("ExchangeTicks", testExchangeTicksSliceDeleteAll)
	t.Run("VSPS", testVSPSSliceDeleteAll)
	t.Run("VSPTicks", testVSPTicksSliceDeleteAll)
	t.Run("VSPTickTimes", testVSPTickTimesSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Exchanges", testExchangesExists)
	t.Run("ExchangeTicks", testExchangeTicksExists)
	t.Run("VSPS", testVSPSExists)
	t.Run("VSPTicks", testVSPTicksExists)
	t.Run("VSPTickTimes", testVSPTickTimesExists)
}

func TestFind(t *testing.T) {
	t.Run("Exchanges", testExchangesFind)
	t.Run("ExchangeTicks", testExchangeTicksFind)
	t.Run("VSPS", testVSPSFind)
	t.Run("VSPTicks", testVSPTicksFind)
	t.Run("VSPTickTimes", testVSPTickTimesFind)
}

func TestBind(t *testing.T) {
	t.Run("Exchanges", testExchangesBind)
	t.Run("ExchangeTicks", testExchangeTicksBind)
	t.Run("VSPS", testVSPSBind)
	t.Run("VSPTicks", testVSPTicksBind)
	t.Run("VSPTickTimes", testVSPTickTimesBind)
}

func TestOne(t *testing.T) {
	t.Run("Exchanges", testExchangesOne)
	t.Run("ExchangeTicks", testExchangeTicksOne)
	t.Run("VSPS", testVSPSOne)
	t.Run("VSPTicks", testVSPTicksOne)
	t.Run("VSPTickTimes", testVSPTickTimesOne)
}

func TestAll(t *testing.T) {
	t.Run("Exchanges", testExchangesAll)
	t.Run("ExchangeTicks", testExchangeTicksAll)
	t.Run("VSPS", testVSPSAll)
	t.Run("VSPTicks", testVSPTicksAll)
	t.Run("VSPTickTimes", testVSPTickTimesAll)
}

func TestCount(t *testing.T) {
	t.Run("Exchanges", testExchangesCount)
	t.Run("ExchangeTicks", testExchangeTicksCount)
	t.Run("VSPS", testVSPSCount)
	t.Run("VSPTicks", testVSPTicksCount)
	t.Run("VSPTickTimes", testVSPTickTimesCount)
}

func TestInsert(t *testing.T) {
	t.Run("Exchanges", testExchangesInsert)
	t.Run("Exchanges", testExchangesInsertWhitelist)
	t.Run("ExchangeTicks", testExchangeTicksInsert)
	t.Run("ExchangeTicks", testExchangeTicksInsertWhitelist)
	t.Run("VSPS", testVSPSInsert)
	t.Run("VSPS", testVSPSInsertWhitelist)
	t.Run("VSPTicks", testVSPTicksInsert)
	t.Run("VSPTicks", testVSPTicksInsertWhitelist)
	t.Run("VSPTickTimes", testVSPTickTimesInsert)
	t.Run("VSPTickTimes", testVSPTickTimesInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("ExchangeTickToExchangeUsingExchange", testExchangeTickToOneExchangeUsingExchange)
	t.Run("VSPTickToVSPUsingVSP", testVSPTickToOneVSPUsingVSP)
	t.Run("VSPTickTimeToVSPTickUsingVSPTick", testVSPTickTimeToOneVSPTickUsingVSPTick)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("ExchangeToExchangeTicks", testExchangeToManyExchangeTicks)
	t.Run("VSPToVSPTicks", testVSPToManyVSPTicks)
	t.Run("VSPTickToVSPTickTimes", testVSPTickToManyVSPTickTimes)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("ExchangeTickToExchangeUsingExchangeTicks", testExchangeTickToOneSetOpExchangeUsingExchange)
	t.Run("VSPTickToVSPUsingVSPTicks", testVSPTickToOneSetOpVSPUsingVSP)
	t.Run("VSPTickTimeToVSPTickUsingVSPTickTimes", testVSPTickTimeToOneSetOpVSPTickUsingVSPTick)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("ExchangeToExchangeTicks", testExchangeToManyAddOpExchangeTicks)
	t.Run("VSPToVSPTicks", testVSPToManyAddOpVSPTicks)
	t.Run("VSPTickToVSPTickTimes", testVSPTickToManyAddOpVSPTickTimes)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Exchanges", testExchangesReload)
	t.Run("ExchangeTicks", testExchangeTicksReload)
	t.Run("VSPS", testVSPSReload)
	t.Run("VSPTicks", testVSPTicksReload)
	t.Run("VSPTickTimes", testVSPTickTimesReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Exchanges", testExchangesReloadAll)
	t.Run("ExchangeTicks", testExchangeTicksReloadAll)
	t.Run("VSPS", testVSPSReloadAll)
	t.Run("VSPTicks", testVSPTicksReloadAll)
	t.Run("VSPTickTimes", testVSPTickTimesReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Exchanges", testExchangesSelect)
	t.Run("ExchangeTicks", testExchangeTicksSelect)
	t.Run("VSPS", testVSPSSelect)
	t.Run("VSPTicks", testVSPTicksSelect)
	t.Run("VSPTickTimes", testVSPTickTimesSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Exchanges", testExchangesUpdate)
	t.Run("ExchangeTicks", testExchangeTicksUpdate)
	t.Run("VSPS", testVSPSUpdate)
	t.Run("VSPTicks", testVSPTicksUpdate)
	t.Run("VSPTickTimes", testVSPTickTimesUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Exchanges", testExchangesSliceUpdateAll)
	t.Run("ExchangeTicks", testExchangeTicksSliceUpdateAll)
	t.Run("VSPS", testVSPSSliceUpdateAll)
	t.Run("VSPTicks", testVSPTicksSliceUpdateAll)
	t.Run("VSPTickTimes", testVSPTickTimesSliceUpdateAll)
}
