// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Exchange     string
	ExchangeTick string
	VSP          string
	VSPTick      string
}{
	Exchange:     "exchange",
	ExchangeTick: "exchange_tick",
	VSP:          "vsp",
	VSPTick:      "vsp_tick",
}
