// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCommStats(t *testing.T) {
	t.Parallel()

	query := CommStats()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCommStatsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommStat{}
	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CommStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCommStatsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommStat{}
	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := CommStats().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CommStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCommStatsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommStat{}
	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CommStatSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CommStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCommStatsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommStat{}
	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CommStatExists(ctx, tx, o.Date)
	if err != nil {
		t.Errorf("Unable to check if CommStat exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CommStatExists to return true, but got false.")
	}
}

func testCommStatsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommStat{}
	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	commStatFound, err := FindCommStat(ctx, tx, o.Date)
	if err != nil {
		t.Error(err)
	}

	if commStatFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCommStatsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommStat{}
	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = CommStats().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testCommStatsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommStat{}
	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := CommStats().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCommStatsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	commStatOne := &CommStat{}
	commStatTwo := &CommStat{}
	if err = randomize.Struct(seed, commStatOne, commStatDBTypes, false, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}
	if err = randomize.Struct(seed, commStatTwo, commStatDBTypes, false, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = commStatOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = commStatTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CommStats().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCommStatsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	commStatOne := &CommStat{}
	commStatTwo := &CommStat{}
	if err = randomize.Struct(seed, commStatOne, commStatDBTypes, false, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}
	if err = randomize.Struct(seed, commStatTwo, commStatDBTypes, false, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = commStatOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = commStatTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CommStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testCommStatsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommStat{}
	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CommStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCommStatsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommStat{}
	if err = randomize.Struct(seed, o, commStatDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(commStatColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := CommStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCommStatsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommStat{}
	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCommStatsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommStat{}
	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CommStatSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCommStatsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CommStat{}
	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CommStats().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	commStatDBTypes = map[string]string{`Date`: `timestamp without time zone`, `RedditSubscribers`: `integer`, `RedditAccountsActive`: `integer`, `TwitterFollowers`: `integer`}
	_               = bytes.MinRead
)

func testCommStatsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(commStatPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(commStatAllColumns) == len(commStatPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CommStat{}
	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CommStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCommStatsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(commStatAllColumns) == len(commStatPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CommStat{}
	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CommStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, commStatDBTypes, true, commStatPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(commStatAllColumns, commStatPrimaryKeyColumns) {
		fields = commStatAllColumns
	} else {
		fields = strmangle.SetComplement(
			commStatAllColumns,
			commStatPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CommStatSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCommStatsUpsert(t *testing.T) {
	t.Parallel()

	if len(commStatAllColumns) == len(commStatPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := CommStat{}
	if err = randomize.Struct(seed, &o, commStatDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CommStat: %s", err)
	}

	count, err := CommStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, commStatDBTypes, false, commStatPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CommStat struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CommStat: %s", err)
	}

	count, err = CommStats().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
