// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testNetworkPeers(t *testing.T) {
	t.Parallel()

	query := NetworkPeers()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testNetworkPeersDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkPeer{}
	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NetworkPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNetworkPeersQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkPeer{}
	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := NetworkPeers().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NetworkPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNetworkPeersSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkPeer{}
	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := NetworkPeerSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := NetworkPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testNetworkPeersExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkPeer{}
	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := NetworkPeerExists(ctx, tx, o.Timestamp, o.Address)
	if err != nil {
		t.Errorf("Unable to check if NetworkPeer exists: %s", err)
	}
	if !e {
		t.Errorf("Expected NetworkPeerExists to return true, but got false.")
	}
}

func testNetworkPeersFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkPeer{}
	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	networkPeerFound, err := FindNetworkPeer(ctx, tx, o.Timestamp, o.Address)
	if err != nil {
		t.Error(err)
	}

	if networkPeerFound == nil {
		t.Error("want a record, got nil")
	}
}

func testNetworkPeersBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkPeer{}
	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = NetworkPeers().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testNetworkPeersOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkPeer{}
	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := NetworkPeers().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testNetworkPeersAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	networkPeerOne := &NetworkPeer{}
	networkPeerTwo := &NetworkPeer{}
	if err = randomize.Struct(seed, networkPeerOne, networkPeerDBTypes, false, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}
	if err = randomize.Struct(seed, networkPeerTwo, networkPeerDBTypes, false, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = networkPeerOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = networkPeerTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := NetworkPeers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testNetworkPeersCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	networkPeerOne := &NetworkPeer{}
	networkPeerTwo := &NetworkPeer{}
	if err = randomize.Struct(seed, networkPeerOne, networkPeerDBTypes, false, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}
	if err = randomize.Struct(seed, networkPeerTwo, networkPeerDBTypes, false, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = networkPeerOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = networkPeerTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NetworkPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testNetworkPeersInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkPeer{}
	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NetworkPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testNetworkPeersInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkPeer{}
	if err = randomize.Struct(seed, o, networkPeerDBTypes, true); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(networkPeerColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := NetworkPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testNetworkPeersReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkPeer{}
	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testNetworkPeersReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkPeer{}
	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := NetworkPeerSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testNetworkPeersSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &NetworkPeer{}
	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := NetworkPeers().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	networkPeerDBTypes = map[string]string{`Timestamp`: `bigint`, `Address`: `character varying`, `IPVersion`: `integer`, `Country`: `character varying`, `LastSeen`: `bigint`, `Latency`: `integer`, `ConnectionTime`: `bigint`, `ProtocolVersion`: `integer`, `UserAgent`: `character varying`, `Services`: `character varying`, `StartingHeight`: `bigint`, `CurrentHeight`: `bigint`}
	_                  = bytes.MinRead
)

func testNetworkPeersUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(networkPeerPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(networkPeerAllColumns) == len(networkPeerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &NetworkPeer{}
	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NetworkPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testNetworkPeersSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(networkPeerAllColumns) == len(networkPeerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &NetworkPeer{}
	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := NetworkPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, networkPeerDBTypes, true, networkPeerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(networkPeerAllColumns, networkPeerPrimaryKeyColumns) {
		fields = networkPeerAllColumns
	} else {
		fields = strmangle.SetComplement(
			networkPeerAllColumns,
			networkPeerPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := NetworkPeerSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testNetworkPeersUpsert(t *testing.T) {
	t.Parallel()

	if len(networkPeerAllColumns) == len(networkPeerPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := NetworkPeer{}
	if err = randomize.Struct(seed, &o, networkPeerDBTypes, true); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert NetworkPeer: %s", err)
	}

	count, err := NetworkPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, networkPeerDBTypes, false, networkPeerPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize NetworkPeer struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert NetworkPeer: %s", err)
	}

	count, err = NetworkPeers().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
