// Code generated by SQLBoiler 3.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Blocks", testBlocksUpsert)

	t.Run("Exchanges", testExchangesUpsert)

	t.Run("ExchangeTicks", testExchangeTicksUpsert)

	t.Run("Githubs", testGithubsUpsert)

	t.Run("Mempools", testMempoolsUpsert)

	t.Run("NetworkPeers", testNetworkPeersUpsert)

	t.Run("NetworkSnapshots", testNetworkSnapshotsUpsert)

	t.Run("PowData", testPowDataUpsert)

	t.Run("Reddits", testRedditsUpsert)

	t.Run("Twitters", testTwittersUpsert)

	t.Run("Votes", testVotesUpsert)

	t.Run("VSPS", testVSPSUpsert)

	t.Run("VSPTicks", testVSPTicksUpsert)

	t.Run("Youtubes", testYoutubesUpsert)
}
