// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSyncHistories(t *testing.T) {
	t.Parallel()

	query := SyncHistories()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSyncHistoriesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SyncHistory{}
	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SyncHistories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSyncHistoriesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SyncHistory{}
	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := SyncHistories().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SyncHistories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSyncHistoriesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SyncHistory{}
	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SyncHistorySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SyncHistories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSyncHistoriesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SyncHistory{}
	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SyncHistoryExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if SyncHistory exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SyncHistoryExists to return true, but got false.")
	}
}

func testSyncHistoriesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SyncHistory{}
	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	syncHistoryFound, err := FindSyncHistory(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if syncHistoryFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSyncHistoriesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SyncHistory{}
	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = SyncHistories().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSyncHistoriesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SyncHistory{}
	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := SyncHistories().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSyncHistoriesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	syncHistoryOne := &SyncHistory{}
	syncHistoryTwo := &SyncHistory{}
	if err = randomize.Struct(seed, syncHistoryOne, syncHistoryDBTypes, false, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}
	if err = randomize.Struct(seed, syncHistoryTwo, syncHistoryDBTypes, false, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = syncHistoryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = syncHistoryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SyncHistories().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSyncHistoriesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	syncHistoryOne := &SyncHistory{}
	syncHistoryTwo := &SyncHistory{}
	if err = randomize.Struct(seed, syncHistoryOne, syncHistoryDBTypes, false, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}
	if err = randomize.Struct(seed, syncHistoryTwo, syncHistoryDBTypes, false, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = syncHistoryOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = syncHistoryTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SyncHistories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testSyncHistoriesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SyncHistory{}
	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SyncHistories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSyncHistoriesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SyncHistory{}
	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(syncHistoryColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := SyncHistories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSyncHistoriesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SyncHistory{}
	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSyncHistoriesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SyncHistory{}
	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SyncHistorySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSyncHistoriesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SyncHistory{}
	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SyncHistories().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	syncHistoryDBTypes = map[string]string{`ID`: `integer`, `TableName`: `character varying`, `Source`: `character varying`, `Date`: `timestamp without time zone`}
	_                  = bytes.MinRead
)

func testSyncHistoriesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(syncHistoryPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(syncHistoryAllColumns) == len(syncHistoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SyncHistory{}
	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SyncHistories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSyncHistoriesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(syncHistoryAllColumns) == len(syncHistoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SyncHistory{}
	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SyncHistories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, syncHistoryDBTypes, true, syncHistoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(syncHistoryAllColumns, syncHistoryPrimaryKeyColumns) {
		fields = syncHistoryAllColumns
	} else {
		fields = strmangle.SetComplement(
			syncHistoryAllColumns,
			syncHistoryPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SyncHistorySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSyncHistoriesUpsert(t *testing.T) {
	t.Parallel()

	if len(syncHistoryAllColumns) == len(syncHistoryPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := SyncHistory{}
	if err = randomize.Struct(seed, &o, syncHistoryDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SyncHistory: %s", err)
	}

	count, err := SyncHistories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, syncHistoryDBTypes, false, syncHistoryPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SyncHistory struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SyncHistory: %s", err)
	}

	count, err = SyncHistories().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
