// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

var TableNames = struct {
	ChartData    string
	Data         string
	EventOne     string
	HistoricData string
	NewTable     string
	Posdata      string
}{
	ChartData:    "chart_data",
	Data:         "data",
	EventOne:     "event_one",
	HistoricData: "historic_data",
	NewTable:     "new_table",
	Posdata:      "posdata",
}
