// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ChartData    string
	Data         string
	HistoricData string
	Posdatatable string
	Powdatatable string
}{
	ChartData:    "chart_data",
	Data:         "data",
	HistoricData: "historic_data",
	Posdatatable: "posdatatable",
	Powdatatable: "powdatatable",
}
